networks:
  inception:

services:
  mariadb:
    container_name: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    

  nginx:
    container_name: nginx
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    ports:
      - 443:443
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    restart: always
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy




volumes:
  db:
    driver: local
  
  wordpress:
    driver: local
  
