networks:
  inception:

services:
  mariadb:
    container_name: mariadb
    restart: always
    volumes:
      - db:/var/www/html
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}

    

  nginx:
    container_name: nginx
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    ports:
      - 443:443
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile

  wordpress:
    container_name: wordpress
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: USER
      WORDPRESS_DB_PASSWORD: passwort
      WORDPRESS_DB_NAME: exampledb




volumes:
  db:
    driver: local
  
  wordpress:
    driver: local
  
