networks:
  inception:

services:
  mariadb:
    container_name: mariadb
    restart: always
    volumes:
      - db:/var/www/html
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD
    

  nginx:
    container_name: nginx
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    ports:
      - 443:443
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile

  wordpress:
    container_name: wordpress
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile



volumes:
  db:
    driver: local
  
  wordpress:
    driver: local
  
